[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Kunal Bhalla <bhalla.kunal@gmail.com>"]
edition = "2018"

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
